### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by qdd1234** [MendelXu/MixTraining#2]
Hi, thanks for your wonderful work! When do you release the source code for the paper？

**Comment by stupidZZ** [comment]
We plan to release the code after CVPR DDL.

**Comment by machengcheng2016** [comment]
@stupidZZ @MendelXu 
It's already after CVPR DDL. When will you release the code, please?😭

**Comment by MendelXu** [comment]
@machengcheng2016 I have updated the code and will upload the retrained model in the next one or two weeks.

**Comment by machengcheng2016** [comment]
@MendelXu 
Cool! Thanks for your quick reply!
