### ISSUE TITLE
paper issue

### ISSUE THREAD

**Issue by qdd1234** [MendelXu/MixTraining#3]
Hi, thanks for your wonderful work. I have a question about your paper that In your paper, you mention that strong augmentation should be applied on targets that can be easily trained on. Whether you do not apply strong augmentation on targets that may be hardly trained on and only use weak data augmentation on them？

**Comment by MendelXu** [comment]
In fact, this makes little difference (soft or hard assignment)...If you have read the paper, you will find this part contributes little to the final result. Maybe there exists a method to apply instance-wise augmentation but I don't think this is the correct way:cry:.
